### ISSUE TITLE
in solar system example all the planets inherit sun color

### ISSUE THREAD

**Issue by makc** [aerys/minko-examples#17]
Looks like you are trying to batch same materials a bit too hard. Only if I create BasicMaterial clone for some planet, its color is set correctly.

**Comment by makc** [comment]
Turns out this may be FP issue. I see this broken in mac 11.7.700.146 sa debugger, the other guy runs the same swf just fine on his computer with 11.4.402.287.

**Comment by makc** [comment]
really wtf. scout records the session with planets colored correctly, but sa player insists on rendering everything yellow. oh well.

**Comment by JMLX42** [comment]
Tested and working with:
Flex SDK 4.9 with AIR 3.7/Flash 11.7 (windows)
Flash player debug 11.7.700.169 (windows)

What version of the FP are you using?

**Comment by makc** [comment]
as of today 11.7.700.169 sa debugger on mac

![screen shot 2013-05-06 at 1 58 25 pm](https://f.cloud.github.com/assets/242577/465807/5699af0e-b644-11e2-8fbb-e0aba5cb26c3.png)

**Comment by warrenseine** [comment]
I'll try in this exact setup later this day. Thanks for reporting.

**Comment by warrenseine** [comment]
@makc Tested on Mac OS X, Flash Player Projector 11.7.700.169. It works here.

I'm closing it because it looks like an isolated issue we can't fight. Please re-open if you consider this is a bug in Minko.

**Comment by makc** [comment]
If only I had an idea what fails here, but I can't even understand where to look for the cause. I will try later with 11.8 and, if it still happens, we will have to go to adobe with this.
