### ISSUE TITLE
can't find some import class 2.0b

### ISSUE THREAD

**Issue by katopz** [aerys/minko-examples#2]
i think some class is missing there, or maybe i just can't find it

via WireframeExample
aerys.minko.render.effect.wireframe.WireframeShader;
aerys.minko.scene.node.mesh.geometry.WireframeGeometry;

via PickingExample
aerys.minko.scene.controller.PickingController;

thanks

**Comment by JMLX42** [comment]
Those samples require the minko-picking and minko-effects extensions and they are not up-to-date for now. They will be released in a few days/weeks.
