### ISSUE TITLE
AnimationController in Mesh?

### ISSUE THREAD

**Issue by alphawolf1988** [aerys/minko-examples#7]
Hey there!

I wonder if the examples with AnimationControler are correct.
The Mesh awaits for the third argument an String but there is passed
an AnimationController. Did i understand something wrong?

Example: https://github.com/aerys/minko-examples/blob/master/src/aerys/minko/example/core/animationcontroller/AnimationControllerExample.as

Regards!

**Comment by JMLX42** [comment]
thank you for your feedback!
fixed in f6124c80847240bb3889eb7d518bf5d1ac4720a4
